#include <msx_fusion.h>
#include <stdlib.h>
#include <string.h>


// Define maximum files per page and screen properties
#define FILES_PER_PAGE 5
#define SCREEN_COLUMNS 40
#define MAX_FILES 100

// File data structure
typedef struct {
    char name[13];  // File name (8.3 format)
    char mapper[10]; // Mapper type
} File;

// Mock file list (we will populate this dynamically by the list generated by the Raspberry Pi PICO)
File files[MAX_FILES] = {
    {"FILE1.BIN", "16K"}, {"FILE2.BIN", "32K"}, {"GAME1.ROM", "KONAMI"},
    {"APP1.COM", "16K"}, {"FILE5.BIN", "32K"}, {"GAME2.ROM", "KONAMI"},
    {"FILE6.BIN", "16K"}, {"FILE7.BIN", "32K"}, {"GAME3.ROM", "KONAMI"},
    {"FILE8.BIN", "16K"}, {"FILE9.BIN", "32K"}, {"GAME4.ROM", "KONAMI"},
    {"FILE10.BIN", "16K"}, {"FILE11.BIN", "32K"}, {"GAME5.ROM", "KONAMI"},
    {"FILE12.BIN", "16K"}, {"FILE13.BIN", "32K"}, {"GAME6.ROM", "KONAMI"}
};

// Current page and file index
int currentPage = 0;
int currentIndex = 0;

// Total file count
int totalFiles = 18; // Update this dynamically if needed

void displayMenu() {
    // Clear the screen
    Cls();
    
    // Display files for the current page
    int startFile = currentPage * FILES_PER_PAGE;
    int endFile = startFile + FILES_PER_PAGE;
    if (endFile > totalFiles) endFile = totalFiles;
    
    for (int i = startFile; i < endFile; i++) {
        if (i == currentIndex) {
            //textcolor(15); // White
           // bgcolor(0);    // Black
        } else {
            //textcolor(0);  // Black
           // bgcolor(15);   // White
        }
        //gotoxy(1, (i - startFile) + 1);
       // printf("%-12s %s", files[i].name, files[i].mapper);
       printf("TESTE");
    }
    
    // Reset colors
    //textcolor(15);
    //bgcolor(0);
}

void navigateMenu() {
    char key;
    while (1) {
        displayMenu();
        //key = getch();

        switch (key) {
            case 0x48: // Up arrow
                if (currentIndex > 0) currentIndex--;
                if (currentIndex < currentPage * FILES_PER_PAGE) {
                    currentPage--;
                }
                break;
            case 0x50: // Down arrow
                if (currentIndex < totalFiles - 1) currentIndex++;
                if (currentIndex >= (currentPage + 1) * FILES_PER_PAGE) {
                    currentPage++;
                }
                break;
            case 0x4D: // Right arrow
                if (currentPage < (totalFiles - 1) / FILES_PER_PAGE) {
                    currentPage++;
                    currentIndex = currentPage * FILES_PER_PAGE;
                }
                break;
            case 0x4B: // Left arrow
                if (currentPage > 0) {
                    currentPage--;
                    currentIndex = currentPage * FILES_PER_PAGE;
                }
                break;
            case ' ': // Space key
            case '\r': // Enter key
                //gotoxy(1, FILES_PER_PAGE + 2);
                //printf("Selected: %s (%s)", files[currentIndex].name, files[currentIndex].mapper);
                return;
            case 0x10: // Shift + Left or Right (for simplicity, use same behavior as arrows)
                if (key == 0x4B && currentPage > 0) {
                    currentPage--;
                } else if (key == 0x4D && currentPage < (totalFiles - 1) / FILES_PER_PAGE) {
                    currentPage++;
                }
                currentIndex = currentPage * FILES_PER_PAGE;
                break;
        }
    }
}

void main() {
    // Initialize MSX Screen 0
    //set_mode(0);
    displayMenu();
    navigateMenu();
    
    
}